xy-planning-network/trails

- http/template/tag_packer.go
- quick and dirty solution for setting the javascript asset path during local development
> refactor: tag packer modern for local dev

- http/example/main.go
- http/resp/responder.go
- http/resp/responder_opt.go
- http/resp/responder_opt_test.go
- http/resp/response.go
- logger/context.go
- logger/doc.go
- logger/logger.go
- logger/logger_test.go
- logger/opt.go
- logger/sentry.go
Previously, `logger.TrailsLogger` inflexibly assumed the caller to a method (`Logger.Debug`, `Logger.Info`, etc.) was a fixed number of steps up in the stack. When an app logged a message, this was fine. Messages looked like:
```
2022/04/29 10:53:58 /tmp/build_1739b51c/procedures/subscription.go:295 'record not found'
```
The problem with this approach was most notably seen when using `resp.Responder` and any of the functional options that log a message (`resp.Err`, `resp.Warn`). The file and line number of the `trails` package was always logged, which was uninformative and not the intention of the end user
```
2022/04/29 10:53:58 [DEBUG] trails@v0.3.14/http/resp/responder.go:41 'such fun!'
```
Now, `logger` introduces another interface `SkipLogger` which allows for setting how many …
> Log message location matches call site through configuration

- http/middleware/authorize.go
- http/middleware/authorize_test.go
- http/middleware/current_user.go
`AuthorizeApplicator` is a generic struct enabling developers to create functions that check whether their application users are authorized to access a resource. This rewrites `ApplyAuthorizer`, which put the onus on developers to accept `any` from `trails` and cast to their local type before checking authorization. Here's functions used by `ApplyAuthorizer` could be rewritten for `AuthorizeApplicator[T].Apply`
**ApplyAuthorizer**
```golang
func hasAccess(u interface{}) (string, bool) {
cu, ok := u.(*User)
if !ok {
return "/", false
}
if cu.AccessState != trails.AccessGranted {
return cu.HomePath(), false
}
return "", true
}
```
Such a function would be used as such:
```golang
router.Route{
Path: "/",
Method: http.MethodGet,
Handler: myHandler,
Middlewares: …
```
> ApplyAuthorizer -> AuthorizeApplicator

- http/middleware/authorize.go
- http/middleware/authorize_test.go
Endpoints that use the `AuthorizeApplicator` were not redirecting properly due to a `401` status code returning and not a proper redirect.
The existing solution was too brittle/narrow. Take a look at the unit tests which support both the header supplying many values and it not. The latter - that the "Accept" header is seen as a single string - is now the expected, "happy path" case.
I am unsure why this stopped working and don't have an interest in scratching the surface too deep. At first I thought it was a Firefox thing, but it isn't. Both Firefox & Chrome's "Accept" headers are parsed as a single long string by `net/http` instead of multiple values.
> Resolves redirect bug

- http/middleware/current_user.go
- http/middleware/current_user_test.go
- http/middleware/middleware_test.go
- postgres/service.go
- ranger/config.go
- ranger/default.go
- ranger/opt.go
- ranger/ranger.go
The setup to get to a `session.UserStorer` that works with an application is not meeting our goals. First, it requires a tango with the application's procedures being configured first before a `*ranger.Ranger` can be constructed. Second, there's more than 1 way to set it up.
To be able to store the `currentUser` in a `*http.Request.Context`, an application must define how to retrieve the `currentUser` from a datastore before `middleware.CurrentUser` can then stash it in the context. For example, from `college-try`:
```go
func main() {
...
procs := procedures.New()
rng, err := ranger.New(
...
ranger.WithUserSessions(userstorer{procs.User.GetByID}),
)
...
}
type userstorer struct {
get func(id uint) (domain.User, error)
}
func (u userstorer) GetByID(id uint) (middleware.User, error) {
user, …
```
> ranger & session.UserStorer refactor

- error.go
- http/resp/response.go
- http/resp/response_test.go
- toolbox.go
- toolbox_test.go
Adding a `Toolbox` to the data to be rendered is a little ungainly; see: [ex. 1](https://github.com/xy-planning-network/college-try/blob/220d23efe095dbc367ad817d3a8ceb252724b8d6/http/web/benefits_handler.go#L63) & [ex. 2](https://github.com/xy-planning-network/college-try/blob/220d23efe095dbc367ad817d3a8ceb252724b8d6/http/web/forms_handler.go#L19-L25).
This PR moves the definitions of `Toolbox`, `Tool` and `ToolAction` found on [`college-try`](https://github.com/xy-planning-network/college-try/blob/master/domain/toolbox.go) to this repo. Check the docs for definitions of each of these.
This PR adds the `http/resp.Fn` `Toolbox` for injecting a toolbox into rendered data. If the `Toolbox` can be rendered, then it is nested under "props" with "toolbox" as its key. If other toolboxes are …
> adds Toolbox, Tool, ToolAction definitions

- postgres/postgres.go
- ranger/default.go
Connections to Postgres should fallback to using the default `sslmode` param instead of `disabled`.
> Update PG connections to fallback to default SSL mode

- http/resp/responder.go
- http/resp/responder_opt.go
- http/resp/response.go
- http/resp/response_test.go
- http/template/parse.go
- ranger/default.go
- ranger/tmpl/layout/additional_scripts.tmpl
- ranger/tmpl/layout/authenticated_base.tmpl
- ranger/tmpl/layout/unauthenticated_base.tmpl
- ranger/tmpl/layout/vue.tmpl
- ranger/tmpl/layout/vue_scripts.tmpl
`ranger` provides 2 [`fs.FS`](https://pkg.go.dev/io/fs#FS) to `http/template` in order to parse its own embedded files and those provided by the application (with the latter overriding any default templates in ranger). The initial use case was to ensure an error page is made as a backstop for unruly `*http/resp.Responder.Html` calls. We can push this paradigm further by including the layout templates every project uses.
This PR creates a new `ranger/tmpl/layout` dir with 5 files, more on those files below. By doing this, development can begin immediately without needing to copy these files from another repo. Only when some additional markup diverging from the minimal defaults is needed would someone begin developing their own layout templates.
- `unauthenticated_base.tmpl` which renders …
> Ranger loads default layout templates

- logger/sentry.go
- ranger/config.go
- ranger/ranger.go
There is no need for flexibility with shutting down plugins, etc. as the only use case is Sentry. Instead, this PR brings in `logger.FlushSentry` and adds it to `*Ranger.shutdowns` when a `*logger.SentryLogger` is at hand.
> Remove ranger.Config.Shutdown

- go.mod
- go.sum
- http/middleware/get_ip_address.go
- http/middleware/log_request.go
- http/middleware/log_request_test.go
- log.go
- ranger/default.go
- ranger/ranger.go
There are 2 problems this PR moves the needle towards solving.
1. Including more data in HTTP router handling logs. Doubling down on AWS, we want to know more about how HTTP requests are handled in our application and be able to trace those requests more reliably. As of now, our implementation of this functionality in the `LogRequest` middleware provides limited information.
2. Our logging lacks ergonomics. With a [`slog`](https://pkg.go.dev/golang.org/x/exp/slog) accepted for implementation in the std lib, let's jump on board.
This PR makes 3 major changes:
1. It moves `LogRequest` to a "post-response" middleware. Some of the data we want to record can only be known after the request is handled (e.g., response status code), so must log the message after the application completes handling …
> replaces logger.Logger in middleware.LogRequest with slog.Logger

- ranger/ranger.go
- ranger/ranger_test.go
The maintenance mode handler was returning a `200 OK` response. This PR:
- Changes the response code to `503`
- Bumps the `retry-after` header to `600` (I figured that for our typical use-case of DB maintenance, `300` might be a bit low -- but I guess it's all pretty arbitrary)
- Adds a test
> Ensure maintenance mode handler responds properly with 503

- .gitignore
- postgres/postgres.go
- ranger/default.go
I debated passing the config through ranger or something else so that it could be completely overrode, but opted to simply remove not found errors and remove color outside of dev. This creates the minimal amount of changes from what we have now while also not allowing more configuration we don't have an immediate use case for.
> Configures gorm logger

- logger/logger.go
Using the `exp` pkg for `slog` meant the API would change before landing in the std lib - and it has! As well, the pkg used for colorizing output made the jump from `exp` to std lib. The type switch to overwrite the source file & line number broke, accordingly.
This PR replaces the type switch for an assertion given the std lib `slog` and `tint` pkg both coalesced on the same type.
> Logger path fix

- http/middleware/log_request.go
- http/session/session.go
- http/session/store.go
- keys.go
Two problems:
1. only authenticated sessions persist between requests; each unauthenticated request starts a new session
- This is because `session.Session.Save` is not called for every session created, and instead was saved only when other methods like adding flashes or registering a user.
2. there's no unique identifier to track sessions across requests
This PR adds a UUID to each session. And, it saves sessions for all requests during the `InjectSession` middleware.
> Add ID for sessions 

- postgres/postgres.go
- ranger/default.go
My research for the performance regression for [this Notion ticket](https://www.notion.so/xylabs/Address-ReconciliationProcedures-Diff-performance-regression-7bfb0299d89249a0b163b10276c30900?pvs=4) led to an interesting finding. The simplest, easiest "win" was to not close/discard idle DB connections. The handler returned 33% faster on average.
Currently, a query opens a database connection and closes it when it completes. There is no default connection pooling enabled.
This PR adds an env var `DATABASE_MAX_IDLE_CXNS` which allows for keeping open a certain number of idle database connections. The number of actual connections can exceed the max, but when queries complete, the connection returns to the pool until the pool equals `DATABASE_MAX_IDLE_CXNS`. If the max has been reached, it …
> Adds DATABASE_MAX_IDLE_CXNS for configuring DB idle connection pooling

- http/router/router.go
- ranger/default.go
- ranger/ranger.go
Requests for assets, distributed client, and not found paths are not logged currently. This hinders observability and debugging.
This PR includes the `middleware.LogRequest` middleware on the handlers for requests to filesystem resources - i.e., the built client and assets. There's a bit of refactoring in here to help with readability.
As well, requests ending up in `404` or `307` because of not found are logged.
> Logs all requests to assets, client, and not found

- postgres/migrate.go
- postgres/postgres.go
- ranger/config.go
- ranger/default.go
- ranger/ranger.go
Migrations run prematurely in app startup. In all use cases, app initialization means constructing a `*ranger.Ranger` before emitting properties from it for other app services, procedures, etc. Because migrations run when establishing the database connection, this is too early in an app's startup. Migrations should be the last operation before starting an app due to the unknowns reversing their schema and data changes.
As well, there are no longer any uses for running migrations when building a worker, so this change of use case needs to be updated in `ranger`.
[Notion ticket](https://www.notion.so/xylabs/Spike-DB-migrations-f73c55740a1546459f6d28d40a162da4?pvs=4)
This PR exports `postgres.MigrateUp` so a `*ranger.Range` can call it in `Guide`. `Guide` is the final step in app startup …
> exports postgres.MigrateUp, call in *ranger.Ranger.Guide

- ranger/ranger.go
I was hoping to be able to check our logs for our currently running Go version to determine our exposure to [CVE-2023-44487](https://github.com/golang/go/issues/63417), and figured this would be a nice add.
> ranger/ranger: logs GoVersion in Guide

- logger/sentry.go
Anywhere else I'm missing where this should get updated?
> Don't send Warn() level logging to sentry

- ranger/default.go
Follow up to #70 after we discovered [deployment issues with AppRunner](https://www.notion.so/xylabs/8f16954aa3494675837f0cceb6a21c95?v=9d015d84f6fa48fe837c8ad0f6ab5be8&p=94385073857946458fd4bfe060573a41&pm=s)
- leaves the `defaultServer` host empty when `HOST` is not set
The goal here is to avoid adding more configuration details to our container based deployments by either requiring another ENV, a change to the Dockerfile, or a change to the AppRunner config.  FWIW, I do expect setting `HOST=0.0.0.0` would also resolve the app runner deployment issue, but Docker networking is difficult to keep top of mind and I just assume stay close to the defaults.  Letting the host stay empty when `HOST` is not set lets local dev setups handle the MacOS firewall warning that initially prompted #70.
> leave default server host empty

- http/middleware/authorize_test.go
- http/resp/responder.go
- http/resp/responder_test.go
- http/resp/response.go
When doing `*Responder.Html(w, r, Authed(), Vue("MyPage"))` - a common pattern in our web handlers - and there is no `currentUser`, no error raises when it should.
A separate bug surfaced here where calling `Url` and `Params` overwrote the query params set. The order shouldn't matter.
This uses `errors.Join` to merge all errors together when looping through the functional options passed to a `Responder` method.
Also, `Url` merges with query params set before it was called.
> http/resp: report all errors

- http/session/store.go
- ranger/default.go
- ranger/doc.go
- ranger/ranger.go
In order for Portal's cookie to be sent in requests to `connect.xyplanningnetwork.com`, we need to set the cookie for our root `xyplanningnetwork.com` domain. Thataways, event handlers for Find an Advisor features can be aware of `currentUser` (cf. [Notion ticket](https://www.notion.so/xylabs/Enable-currentUser-check-on-for-Find-an-Advisor-events-1bcce20905a5476f978d7389c5b12415?pvs=4)).
This PR adds `SESSION_DOMAIN` for enabling this configuration.
> adds SESSION_DOMAIN for specifying the domain to set on session cookies

- ranger/tmpl/layout/authenticated_base.tmpl
- ranger/tmpl/layout/unauthenticated_base.tmpl
I ran into this when attempting to read `.Data` in the `additional_scripts.tmp` template.  As far as I can tell, these are the only template calls that weren't passing data along.
> add cursor to template calls

- http/resp/responder_opt_test.go
- http/resp/responder_test.go
- logger/context.go
- logger/context_test.go
- logger/logger.go
- ranger/default.go
- ranger/ranger_test.go
This PR makes `logger.Logger` environment aware by adding a new param when constructing its `logger.TrailsLogger` implementation. That `Environment` is factored in `logger.LogContext`. Now, when not in dev, the context's request's body and form do not print.
It is useful once in a blue moon to have the raw `*http.Request.Form` or `*http.Request.Body` in the server's logs (as opposed to watching requests in browser dev tools), so opted to keep this around instead of removing entirely.
Fixes DEV-3053
> logger: only prints *http.Request.Body or Form if in dev

- http/session/store.go
- ranger/default.go
Allows setting `SESSION_SAMESITE_MODE` to "Strict", "Lax", or "None".  Defaults to "Lax".
> allow config for same site mode

- http/resp/response.go
- http/resp/response_test.go
- keys.go
This PR enables resolving DEV-3094 according to the std lib's approved pattern. [context/Context.Value](https://pkg.go.dev/context#Context.Value) suggests using, what I'm interpreting as, a getter/setter pattern and not exposing the actual const used to store values in a `context.Context`.
The extra guarding, typing, etc. may appear overkill for our uses, but, there's an argument to be made that if we had followed this advice in the first place, we wouldn't have had the unexpected effect we do have of overwriting values in a `context.Context`. So, taking our lumps on this one.
If we're liking this pattern in general, the next step is to move the other keys over to a similar approach. I'd look into the possibility of generics here, but not likely it'll cut down on boilerplate since the …
> unexports appPropsKey, exposes interacting with it through AppProps

- http/middleware/log_request.go
- http/middleware/log_request_test.go
I was trying to figure out why I wasn't ever seeing any referrer info in our logs, then realized we have better spellcheck than the original author of the spec. (see https://en.wikipedia.org/wiki/HTTP_referer)
> Fix HTTP Referer header name

- account.go
- http/middleware/current_user.go
- http/middleware/middleware_test.go
- http/session/session.go
- http/session/store.go
- logger/context.go
- logger/context_test.go
- logger/doc.go
- model.go
- ranger/config.go
- user.go
Replaces `uint` with `int64`.
⚠️ Subtle breaking change. Don't hump to the new minor version unless ready to take the plung. May be tough to debug otherwise. But, this change requires updating `User.ID` in a codebase to `int64` - unless it uses `trails.Model` - to keep session stores humming along.
> uint -> int64 #minor

- postgres/postgres.go
This formalizes the function that [`gorm.Scopes`](https://github.com/go-gorm/gorm/blob/a9d27293de2267a36fa6c9f8892977d3159cf8ea/chainable_api.go#L376-L380) accepts. This aids DX in small ways:
1. Provides documentation for how to use scopes
2. Simplifies discovering scopes with a grep-able name
3. Simplifies code completion (i.e., `postgres.Scope` instead of `func(db *gorm.DB) *gorm.DB`
In the future, we can imagine `Scope` having helpers attached as methods. By having the type already in place, it'll be less updates.
For how this is used, cf. https://github.com/xy-planning-network/college-try/pull/1837
> [DEV-3407] postgres/postgres: defines Scope

- postgres/migrate.go
- postgres/postgres.go
- ranger/ranger.go
Moves away from hardcoding `public` in different calls setting up the DB. We can find a more elegant API down the line, but this gets the job done!
For an example: https://github.com/xy-planning-network/college-try/pull/1921
> [DEV-3407] enables setting PostgreSQL schema for DB
